spring:
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat

baidu:
  ocr:
    app-id: 123
    api-key:  xxx
    secret-key: yyy
    general-url: https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic
    accurate-url: https://aip.baidubce.com/rest/2.0/ocr/v1/accurate_basic
    access-token-url: https://aip.baidubce.com/oauth/2.0/token

server:
  port: 8899